### ISSUE TITLE
Play Playlist

### ISSUE THREAD

**Issue by josh929800** [keatontaylor/custom_components#102]
In the old version (pre 1.0.0), I was using something along the line of:  
     - id: Blank Playlist
        name: Blank Playlist
        type: AMAZON_MUSIC
This stoped working (I think it was working yesterday on 1.0.0 but I could be wrong). I also use type: TUNEIN and it appears to still be working.

**Comment by alandtse** [comment]
What happens in the Alexa App if you create a test routine with this information and try to play it?

Please also provide the specific JSON you are using so we can test it and specify what you mean that it "stopped working."  Does Alexa say anything? Does nothing happen?

**Comment by josh929800** [comment]
Original code:
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "Josh's Playlist",   "media_content_type": "AMAZON_MUSIC" 
}
“I can’t find songs by Josh’s Playlist”
I Also tried…
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "Joshs Playlist",   "media_content_type": "AMAZON_MUSIC" 
}
“I can’t find songs by Joshs Playlist”
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "JoshsPlaylist",   "media_content_type": "AMAZON_MUSIC" 
}
“I can’t find songs by JoshsPlaylist”


Also tried…
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "Alexa.Music.PlayJoshs",   "media_content_type": "sequence" 
}
No Response from the echo.
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "Alexa.Music.PlayJoshsPlayist",   "media_content_type": "sequence" 
}
No Response from the echo.

This used to play the podcast Chompers from Tune In now it says "You have chompers enabled would you like to open it?"
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "Chompers",   "media_content_type": "TUNEIN" 
}

As for the test I have created it... and verified that it is there...
  {
    "@type": "com.amazon.alexa.behaviors.model.Automation", 
    "automationId": "amzn1.alexa.automation.c6059e15-5b78-4b8f-81d2-************", 
    "condition": null, 
    "creationTimeEpochMillis": 1551351665006, 
    "lastUpdatedTimeEpochMillis": 1551351665006, 
    "name": null, 
    "sequence": {
      "@type": "com.amazon.alexa.behaviors.model.Sequence", 
      "sequenceId": "amzn1.alexa.sequence.4b2b506a-9475-4f72-ba74-************", 
      "startNode": {
        "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode", 
        "name": null, 
        "operationPayload": {
          "customerId": "**************", 
          "deviceSerialNumber": "ALEXA_CURRENT_DSN", 
          "deviceType": "ALEXA_CURRENT_DEVICE_TYPE", 
          "locale": "en-US", 
          "musicProviderId": "TUNEIN", 
          "sanitizedSearchPhrase": "chompers", 
          "searchPhrase": "Chompers"
        }, 
        "type": "Alexa.Music.PlaySearchPhrase"
      }
    }, 
    "status": "ENABLED", 
    "triggers": [
      {
        "id": "amzn1.alexa.trigger.1ca5ca3e-62b7-4cc0-b7cb-************", 
        "payload": {
          "customerId": "**************", 
          "locale": "en-US", 
          "marketplaceId": "*************", 
          "utterance": "test"
        }, 
        "timeLapse": null, 
        "type": "CustomUtterance"
      }
    ]
  }, 
When I run this... Nothing happens...
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "test",   "media_content_type": "routine" 
}

**Comment by alandtse** [comment]
Can you please use the ``` to try to quote the text so it doesn't destroy the whitespace. I'll edit your first one to show you how.

**Comment by josh929800** [comment]
```json
{
  "entity_id": "media_player.josh_s_tap",   "media_content_id": "Alexa.Music.Play",   "media_content_type": "sequence" 
 }
```
This will play music but If I try to enter anything after Play there is no response.

**Comment by alandtse** [comment]
Thanks for the details. Answers inline.

> Original code:
> 
> ```json
> {
>   "entity_id": "media_player.josh_s_tap",   "media_content_id": "Josh's Playlist",   "media_content_type": "AMAZON_MUSIC" 
> }
> ```
> 
> “I can’t find songs by Josh’s Playlist”
> I Also tried…
> 
> ```json
> {
>   "entity_id": "media_player.josh_s_tap",   "media_content_id": "Joshs Playlist",   "media_content_type": "AMAZON_MUSIC" 
> }
> ```
> 
> “I can’t find songs by Joshs Playlist”
> 
> ```json
> {
>   "entity_id": "media_player.josh_s_tap",   "media_content_id": "JoshsPlaylist",   "media_content_type": "AMAZON_MUSIC" 
> }
> ```
> 
> “I can’t find songs by JoshsPlaylist”
> 
Can you get it to work with an [Alexa routine](https://www.amazon.com/gp/help/customer/display.html?nodeId=G202200080)? 

Everything below until my next coment will definitely not work since sequences do not allow you to change anything.
> Also tried…
> 
> ```json
> {
>   "entity_id": "media_player.josh_s_tap",   "media_content_id": "Alexa.Music.PlayJoshs",   "media_content_type": "sequence" 
> }
> ```
> 
> No Response from the echo.
> 
> ```json
> {
>   "entity_id": "media_player.josh_s_tap",   "media_content_id": "Alexa.Music.PlayJoshsPlayist",   "media_content_type": "sequence" 
> }
> ```
> 
> No Response from the echo.
> 
> This used to play the podcast Chompers from Tune In now it says "You have chompers enabled would you like to open it?"
> 
> ```json
> {
>   "entity_id": "media_player.josh_s_tap",   "media_content_id": "Chompers",   "media_content_type": "TUNEIN" 
> }
> ```
> 
If it used to work but doesn't work now, that may be an Amazon issue. Are you saying since updating versions or without changing version?

> As for the test I have created it... and verified that it is there...
> 
> ```json
> {
>    "@type": "com.amazon.alexa.behaviors.model.Automation", 
>    "automationId": "amzn1.alexa.automation.c6059e15-5b78-4b8f-81d2-************", 
>    "condition": null, 
>    "creationTimeEpochMillis": 1551351665006, 
>    "lastUpdatedTimeEpochMillis": 1551351665006, 
>    "name": null, 
>    "sequence": {
>      "@type": "com.amazon.alexa.behaviors.model.Sequence", 
>      "sequenceId": "amzn1.alexa.sequence.4b2b506a-9475-4f72-ba74-************", 
>      "startNode": {
>        "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode", 
>        "name": null, 
>        "operationPayload": {
>          "customerId": "**************", 
>          "deviceSerialNumber": "ALEXA_CURRENT_DSN", 
>          "deviceType": "ALEXA_CURRENT_DEVICE_TYPE", 
>          "locale": "en-US", 
>          "musicProviderId": "TUNEIN", 
>          "sanitizedSearchPhrase": "chompers", 
>          "searchPhrase": "Chompers"
>        }, 
>        "type": "Alexa.Music.PlaySearchPhrase"
>      }
>    }, 
>    "status": "ENABLED", 
>    "triggers": [
>      {
>        "id": "amzn1.alexa.trigger.1ca5ca3e-62b7-4cc0-b7cb-************", 
>        "payload": {
>          "customerId": "**************", 
>          "locale": "en-US", 
>          "marketplaceId": "*************", 
>          "utterance": "test"
>        }, 
>        "timeLapse": null, 
>        "type": "CustomUtterance"
>      }
>    ]
>  }, 
> ```
> 
> When I run this... Nothing happens...
> 
> ```json
> {
>   "entity_id": "media_player.josh_s_tap",   "media_content_id": "test",   "media_content_type": "routine" 
> }
> ```
`routine` is broken if you only have a single step. Fix is in #90 and will be in the next release. Work around is to add one extra dummy step like a volume change.

**Comment by alandtse** [comment]
Oh, try this if the playlist is called "Josh’s Playlist"
```json
{
  "entity_id": "media_player.josh_s_tap",
  "media_content_id": "My playlist Josh’s Playlist",
  "media_content_type": "AMAZON_MUSIC"
}
```

**Comment by josh929800** [comment]
```json
{
  "entity_id": "media_player.josh_s_tap",
  "media_content_id": "My playlist Joshs",
  "media_content_type": "AMAZON_MUSIC"
}
```
For the win! Thank You we are backup and rinning.

**Comment by alandtse** [comment]
Great. I'll close this.
