### ISSUE TITLE
radio station change

### ISSUE THREAD

**Issue by cyberfly79** [keatontaylor/custom_components#104]
Hi,

In the chronological order the following happened (HA: 0.86.4 on raspbian)
1. only alexa_remote_control - worked fine
2. media_player.alexa (0.10.1) worked fine, but alexa_remote_conrol did not work
3. since yesterday media_player.alexa is not working partially (play, pause, volume, status OK), alexa_remote_control is OK.

If media_player.alexa was good:
(changed station)
media_player.play_media
{
  "entity_id": "media_player.my_echo_dot",
  "media_content_id": "XYXY",
  "media_content_type": "TUNEIN"
}

now does not change the station, but alexa_remote_control does it again (./alexa_remote_control.sh -d 'My Echo Dot' -r s1579)

What happened?

Cyber

**Comment by alandtse** [comment]
alexa_remote_control is not related to this component so I can't help you there. 

Are you able to use an [Alexa routine in the Alexa App to play the station you want](https://www.amazon.com/gp/help/customer/display.html?nodeId=G202200080)?  If it doesn't work in the Alexa App, it might be something we can't fix.

If it does work, you can help discover the workin command using this [link](https://github.com/keatontaylor/custom_components/wiki/Sequence-Discovery). I'll need the sequence here.

**Comment by alandtse** [comment]
Please check the notes [here](https://github.com/keatontaylor/custom_components/wiki#query-errors) as users are reporting inconsistent behavior with Amazon. I'll close this but feel free to reopen if your issue isn't resolved.
