### ISSUE TITLE
variable tts to alexa

### ISSUE THREAD

**Issue by nmsoares** [keatontaylor/custom_components#108]
Hi, congrats on this!
I've been trying to pass a the message as variable text to media_player.alexa_tts but it does not seam to work. 
Bellow is my configuration... any ideias why it's not working ?

tap_action:
            action: call-service
            service: media_player.alexa_tts
            service_data:
              entity_id: media_player.second_floor
              message: "{{states.input_text.tts_text.state}}"

**Comment by alandtse** [comment]
Please search the [forum](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/2150) or [wiki](https://github.com/keatontaylor/custom_components/wiki/Automation-examples#tts) for configuration questions.
