### ISSUE TITLE
Alexa Media did not allow re-configure so tried to reinstall Integration and get Server 500 error

### ISSUE THREAD

**Issue by nytram-md** [keatontaylor/custom_components#1392]
**Describe the bug**
I am on latest HA 2021.10.6 but had this issue for a week or more.

I went to the integration and I didnt have the option to re-configure Alexa Media. I waited for a fix (just in case) but nothing pertained.

So I tried to uninstall the integration but I cannot get the integration installed/configured now. I fill in all the usual fields and change amazon.com to .co.uk as in UK. 

![image](https://user-images.githubusercontent.com/55548608/139386470-7fb0c472-4fc9-4b2e-afde-337ac06f3c5e.png)

My Microsoft Authenticator 2FA still works with Amazon website and I have tried this also in the config of the integration but still I get this

![image](https://user-images.githubusercontent.com/55548608/139387041-dd402de7-2a77-4734-85a2-aa64f86e514b.png)

then it takes me back to the config page again with this at the top

![image](https://user-images.githubusercontent.com/55548608/139387212-1ab8c30c-f440-4075-a8c4-1d73f80d0f73.png)

My setup is on proxmox with the HA OS full install and all up to date with OS 6.5.

if you need more info, just ask and ill try and provide.

Thanks

Martyn

**Comment by marciogranzotto** [comment]
@nytram-md how did you fix the problem? I have the same issue
