### ISSUE TITLE
Requirements for alexa_media not found: ['alexapy==1.26.8']. [HA Core 2023.1.7]

### ISSUE THREAD

**Issue by DarthSonic** [keatontaylor/custom_components#1942]
After upgrading from 4.6.2 to 4.6.4:

Logger: homeassistant.setup
Source: setup.py:202
First occurred: 15:56:46 (1 occurrences)
Last logged: 15:56:46

Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.26.8'].

Home Assistant 2023.1.7
Frontend 20230110.0 - latest

**Comment by DarthSonic** [comment]
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 15:56:07 (3 occurrences)
Last logged: 15:56:46

Unable to install package alexapy==1.26.8: ERROR: Cannot install alexapy==1.26.8 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.2.2 -> 23.1.2 [notice] To update, run: pip install --upgrade pip

**Comment by DarthSonic** [comment]
Any info when new release is published or where to find info how to fix it?

**Comment by alandtse** [comment]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Comment by DarthSonic** [comment]
Meanwhile I found this trying to manually install alexapy:

`  × Building wheel for aiohttp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-310
      creating build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/worker.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_ws.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_urldispatcher.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_server.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_runner.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_routedef.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_response.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_request.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_protocol.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_middlewares.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_log.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_fileresponse.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_exceptions.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web_app.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/web.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/typedefs.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/tracing.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/test_utils.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/tcp_helpers.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/streams.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/resolver.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/pytest_plugin.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/payload_streamer.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/payload.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/multipart.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/log.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/locks.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/http_writer.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/http_websocket.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/http_parser.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/http_exceptions.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/http.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/helpers.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/hdrs.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/formdata.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/cookiejar.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/connector.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/client_ws.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/client_reqrep.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/client_proto.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/client_exceptions.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/client.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/base_protocol.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/abc.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/__init__.py -> build/lib.linux-armv7l-cpython-310/aiohttp
      running egg_info
      writing aiohttp.egg-info/PKG-INFO
      writing dependency_links to aiohttp.egg-info/dependency_links.txt
      writing requirements to aiohttp.egg-info/requires.txt
      writing top-level names to aiohttp.egg-info/top_level.txt
      reading manifest file 'aiohttp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'aiohttp' anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching '*.dll' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.obj' found anywhere in distribution
      warning: no previously-included files found matching 'aiohttp/*.html'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE.txt'
      writing manifest file 'aiohttp.egg-info/SOURCES.txt'
      copying aiohttp/_cparser.pxd -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/_find_header.pxd -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/_headers.pxi -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/_helpers.pyi -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/_helpers.pyx -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/_http_parser.pyx -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/_http_writer.pyx -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/_websocket.pyx -> build/lib.linux-armv7l-cpython-310/aiohttp
      copying aiohttp/py.typed -> build/lib.linux-armv7l-cpython-310/aiohttp
      creating build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/_cparser.pxd.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/_find_header.pxd.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyi.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyx.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/_http_parser.pyx.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/_http_writer.pyx.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/_websocket.pyx.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      copying aiohttp/.hash/hdrs.py.hash -> build/lib.linux-armv7l-cpython-310/aiohttp/.hash
      running build_ext
      building 'aiohttp._websocket' extension
      creating build/temp.linux-armv7l-cpython-310
      creating build/temp.linux-armv7l-cpython-310/aiohttp
      /github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -D__ARM_PCS_VFP=1 -I/github/workspace/spk/python310/work-armv7-7.1/install//var/packages/python310/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /github/workspace/spk/python310/work-armv7-7.1/install/var/packages/python310/target/lib -I /github/workspace/spk/python310/work-armv7-7.1/install/var/packages/python310/target/include -I/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -D__ARM_PCS_VFP=1 -I/github/workspace/spk/python310/work-armv7-7.1/install//var/packages/python310/target/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -L /github/workspace/spk/python310/work-armv7-7.1/install/var/packages/python310/target/lib -I /github/workspace/spk/python310/work-armv7-7.1/install/var/packages/python310/target/include -fPIC -I/volume1/@appstore/homeassistant/env/include -I/var/packages/python310/target/include/python3.10 -c aiohttp/_websocket.c -o build/temp.linux-armv7l-cpython-310/aiohttp/_websocket.o
      error: command '/github/workspace/toolchain/syno-armv7-7.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects`

Still cannot find any solution in issues or faq for my problem.
