### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by mihalski** [keatontaylor/custom_components#20]
```
File "/config/custom_components/media_player/alexa.py", line 677
    xcept Exception as ex:
                  ^
SyntaxError: invalid syntax
```

**Comment by keatontaylor** [comment]
There isn't a syntax error as far as I can tell, but line 677 also doesn't contain the code the error is giving you. So I'd guess there might've been an error when you copy and pasted the Alexa.py file from the repo.

**Comment by mihalski** [comment]
Right you are!
Something must have gone wrong when I was downloading the file. On to the next error :P
