### ISSUE TITLE
Captcha loop for non-EN domains

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/custom_components#28]
Moving this issue to its own so we can declutter #14.

I haven't tested it, but perhaps we change the Accept-Language header to "*" so we can accept whatever Amazon gives us and avoid having to check per region.
@dreimer1986, can you check?

**Comment by alandtse** [comment]
No idea if this [version](https://github.com/alandtse/custom_components/blob/debug/media_player/alexa.py) will fix it, but I found a Referer header issue and fixed it while debugging.  This also has more debugging enabled too.

**Comment by dreimer1986** [comment]
Where can I find the debugging for that component?

**Comment by alandtse** [comment]
Ok. You can delete that gist now.  It says you're logging in properly using the saved cookie.  The standby is also normal when the devices aren't playing music.  They never change for you? You said you can use TTS right?

**Comment by alandtse** [comment]
As a note, I don't think the Referrer is the main issue here. I am debugging this with another German user. For anyone running into this, I'm wondering if there could be some issues if the captcha is showing unicode characters.  Does it ever ask or is it just ascii?

**Comment by alandtse** [comment]
In investigating this further, I don't think the captcha loop was tied to languages. I have one additional German user who had a similar issue, but I'll close this one for now. #34 may actually be the root cause.
