### ISSUE TITLE
amazon.it tested not full working

### ISSUE THREAD

**Issue by dustardly** [keatontaylor/custom_components#31]
Imported beta echo dot in italian using "amazon.it" in configuration.yaml , echo is imported and show music, but don't accept tts commands. Fix it in next version if you can, thanks.

**Comment by mihalski** [comment]
I guess this is a FAQ.
```
The TTS issue is a known limitation because of the way the media_player works in HA. You can still call tts through the media_player.alexa_tts service. Check the community thread for instructions.
```

**Comment by dustardly** [comment]
Sorry but i tested in amazon.com with another echo and fully working , while in amazon.it with the other echo dot not working, don't understand tts commands. Your answer is not related to my question, I'm betatesting it language . At the moment alexa.amazon.it is only for betauser . While .com and .uk .fr .au plug in Alexa.py is full working .it at the moment failed. Woking at 50% show what I play on my echo dot it but don't execute any tts message by media_player.alexa_tts service

**Comment by mihalski** [comment]
Sorry, I incorrectly assumed you were trying to use TTS via the web ui.

**Comment by dustardly** [comment]
it work only in echo dot  supported for now .com .de .au .fr not for .it I think is just few code need to integrate .it in configuration of plugin

**Comment by alandtse** [comment]
@dustardly 
We'll probably need the capabilities information from https://alexa.amazon.it/api/devices-v2/device for the echo device. Don't paste the full json but just the specific string.

```json
"capabilities":["CUSTOM_ALARM_TONE","I_HEART_RADIO","PANDORA","MICROPHONE","ACTIVE_AFTER_FRO","PAIR_BT_SINK","REMINDERS","FAR_FIELD_WAKE_WORD","AUDIO_PLAYER","ASCENDING_ALARM_VOLUME","SALMON","SUPPORTS_CONNECTED_HOME","SLEEP","SOUND_SETTINGS","KINDLE_BOOKS","PAIR_BT_SOURCE","PERSISTENT_CONNECTION","AUDIBLE","TUNE_IN","DEREGISTER_FACTORY_RESET","FLASH_BRIEFING","UPDATE_WIFI","SUPPORTS_CONNECTED_HOME_ALL","SUPPORTS_SOFTWARE_VERSION","SET_LOCALE","DREAM_TRAINING","REQUIRES_OOBE_FOR_SETUP","TIMERS_AND_ALARMS","CHANGE_NAME","GOLDFISH","AMAZON_MUSIC","VOLUME_SETTING","POPTART","LEMUR_ALPHA","DEREGISTER_DEVICE","VOICE_TRAINING","EARCONS","PAIR_REMOTE"]
```

Given it's still an Amazon beta, it's possible we'll only have limited success depending on what Amazon has actually enabled.

**Comment by keatontaylor** [comment]
A little background. Both music selection via play media and tts use Alexa routines. If your region does not support routines within the Alexa app those features will not work.

**Comment by dustardly** [comment]
`"capabilities":["FLASH_BRIEFING","PERSISTENT_CONNECTION","UPDATE_WIFI","LEMUR_ALPHA","SALMON","SLEEP","FAR_FIELD_WAKE_WORD","TUNE_IN","TIMERS_AND_ALARMS","AMAZON_MUSIC","ASCENDING_ALARM_VOLUME","I_HEART_RADIO","PAIR_BT_SINK","AUDIBLE","VOLUME_SETTING","GOLDFISH","SUPPORTS_SOFTWARE_VERSION","KINDLE_BOOKS","POPTART","ACTIVE_AFTER_FRO","REMINDERS","REQUIRES_OOBE_FOR_SETUP","PAIR_REMOTE","PANDORA","MICROPHONE","CHANGE_NAME","CUSTOM_ALARM_TONE","VOICE_TRAINING","EARCONS","SUPPORTS_CONNECTED_HOME_CLOUD_ONLY","DEREGISTER_DEVICE","DEREGISTER_FACTORY_RESET","SET_LOCALE","AUDIO_PLAYER","SOUND_SETTINGS","DREAM_TRAINING","PAIR_BT_SOURCE"],`

**Comment by dustardly** [comment]
I tested again is not Amazon.it that not working is Amazon plus that not working  on tts command I don't know why

**Comment by alandtse** [comment]
@dustardly I saw in the community thread Italian is working for you now. I'll go ahead and close this.
