### ISSUE TITLE
Allow for multiple accounts using the component

### ISSUE THREAD

**Issue by boojew** [keatontaylor/custom_components#37]
I have a use case where I have echos that are on distinct accounts to intentionally restrict them from smarthome features, so that my kids can't torture each other, but I would love to be able remotely control them. Can the ability to have multiple accounts be added?

**Comment by alandtse** [comment]
@boojew Just to confirm, the echos are on accounts where the echos are not shared between the accounts right?

**Comment by alandtse** [comment]
If you're brave and ok with a dev build with breaking configuration changes, there is a fix in the 1.0.0 branch I'm working on with instructions [here](https://github.com/keatontaylor/custom_components/wiki/Configuration#versions--100).
