### ISSUE TITLE
Possibility to control volume while media_player in standby mode

### ISSUE THREAD

**Issue by tlpbu** [keatontaylor/custom_components#43]
Thank you for your work put in to this component.

Please add possibility to change Echo device volume while it is in `standby` state.

Currently volume can be changed when media_player in Home Assistant is in state `playing` and `paused` but in order to make alexa_tts service constantly speak text at certain volume.

**Comment by anrada73** [comment]
i wait to

**Comment by niemyjski** [comment]
This would be super useful and it would be awesome to have so I could make her quieter at night and louder during the day. Would be awesome to be able to mute them too.
