### ISSUE TITLE
Device does not show when playing radio stations

### ISSUE THREAD

**Issue by jchasey** [keatontaylor/custom_components#44]
When a specific piece of media is being played it shows all the info as expected.

However if a Radio station is being played on the device the media information is just set to 'standby'. Can the radio information be exposed in the media information attributes?

**Comment by alandtse** [comment]
Do you have an example radio station we can test this on where you see this behavior? For I Heart Radio, I am seeing the ratio station information.

**Comment by jchasey** [comment]
I now get a radio station image being shown correctly - this was fixed on an update some releases ago.
