### ISSUE TITLE
TTS not work

### ISSUE THREAD

**Issue by NDNELSON** [keatontaylor/custom_components#47]
I cant get alexa tts in my echo plus. I want spanish tts .Im from mexico and I try to conect to http://alexa.amazon.com.mx but not work. It only work with amazon.com. But i get this error in log Updating alexa media_player took longer than the scheduled update interval 0:00:10 and sometimes this error Error executing service &lt;ServiceCall tts.google_say AttributeError: 'NoneType' object has no attribute 'group'  any idea?

**Comment by alandtse** [comment]
Looks like it's [working](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/1431).
