### ISSUE TITLE
Volume, Tunein

### ISSUE THREAD

**Issue by anrada73** [keatontaylor/custom_components#49]
Please add possibility to change Echo device volume and select tunein station via json?

**Comment by niemyjski** [comment]
I think tune in is outside of the scope but volume I could see. Perhaps it would forward any payload you send onto Alexa?

**Comment by keatontaylor** [comment]
Volume will be updated to the new routines API. As for tune in this is already a function.

https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/1463
