### ISSUE TITLE
Updating alexa media_player took longer than the scheduled update interval

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/custom_components#50]
Need to figure out how to avoid this error. I don't think it's a functional problem and we can still get accepted into HA with this error but it's not desirable.

**Comment by Kanga-Who** [comment]
Is there any update on a fix for this, this is fillings up my logs with 100's of messages a day. Can we comment out a particular line in the code to prevent the messages?

**Comment by alandtse** [comment]
@Kanga-Who No fix yet as it will require properly breaking this custom component apart from the API (#14) along with other clean up.

As for suppressing the error, it's a HA log error when a component does not respond after a specific interval. You'll need to adjust HA configuration to avoid it entirely.

**Comment by alandtse** [comment]
This may be resolved with the changes we made in 1.0.0. I'll close this for now; please feel free to reopen if you see it again.
