### ISSUE TITLE
Cannot use if/else statement in message

### ISSUE THREAD

**Issue by glassbase** [keatontaylor/custom_components#55]
I was trying to send a message to my Echos using if/else statement to change message depending on certain factors - like you can using the notify services. I assumed it would work with your custom alexa media player but it does not. Not sure if it can be worked in or not.

Example:
```
media_player.alexa_tts
{
"entity_id":"echo"
"message": "{% if ('sensor.somesensor', true) %}this{% else %}that{% endif %}"
}
```

**Comment by remcotim** [comment]
Templating does work. Test it in the dev tools. For a working example, look at the wiki.

**Comment by alandtse** [comment]
Closing given the wiki examples. Please reopen if that doesn't work.

**Comment by glassbase** [comment]
It does not work for me. As a simple example (that works under dev info)...

```
{
"entity_id":"media_player.living_room_echo_dot",
"message":"{% if 1 == 1%}hello{% else %}bye{% endif %}"
}
```

It announces "if 1 1 hellow else bye endif"

**Comment by alandtse** [comment]
Call services will not process the template. You need to use a data_template per the automation or script examples for HA to actually process the template.
