### ISSUE TITLE
Add component to custom_updater

### ISSUE THREAD

**Issue by h4nc** [keatontaylor/custom_components#58]
As I mentioned before in the home assistant commnuity support thread to this component, it would be nice so have a possibility to autoupdate this. This would be possible if add this to the custom updater component. 

https://github.com/custom-components/custom_updater?files=1

**Comment by lizaoreo** [comment]
I second this request :-)

Here are the steps to add support for it:

https://github.com/custom-components/custom_updater/wiki/components

**Comment by Beertje135** [comment]
After all great work this would be a mayor great update. Thanks for all the work!

**Comment by niemyjski** [comment]
This would be awesome.

**Comment by vMeph** [comment]
plz @alandtse  make this happen:)
thanks, awsome job

**Comment by alandtse** [comment]
It's on my todo list. Couldn't do it before since we were going to change the file name structures.

**Comment by alandtse** [comment]
Would you guys be ok with the install button not working but you'd at least get the new version notification? I opened an [issue](https://github.com/custom-components/custom_updater/issues/98) at custom_updater to confirm it can do installs for multiple files as it doesn't look like it's supported yet.

**Comment by h4nc** [comment]
The install button would only not work for your component, right? Not for every component in customuodater?

**Comment by h4nc** [comment]
I think it would be fine for now to get the notification only.
You opened that issue maybe this will be fixed soon, till than this solution would be ok.

**Comment by Obicom** [comment]
I would agree .. as a first step better then nothing ... but target scenario should be also the update via button.

**Comment by alandtse** [comment]
Ok, I'll plan to only have a notification only until the feature is added. My target scenario is to get this in HA so it's not a custom_component so I might prioritize that. 😄

**Comment by h4nc** [comment]
So is this notification only now or does it also update?

**Comment by alandtse** [comment]
Updates. They added the support we needed.

**Comment by sagitt** [comment]
where is documentation about this?

what is the custom updater link?

**Comment by h4nc** [comment]
It’s in the wiki.
