### ISSUE TITLE
alexa tts

### ISSUE THREAD

**Issue by dramos0898** [keatontaylor/custom_components#6]
Hello, 
I had everything working fine, then i started getting errors so i updated the alexa.py file.. but now i home assistant can't find any devices and i get this error in the log:

"2018-07-18 17:04:08 WARNING (MainThread) [homeassistant.core] Unable to find service media_player/alexa_tts"

am i doing something wrong?

Best regards,
Diogo Ramos

**Comment by keatontaylor** [comment]
I'd suggest looking at the community forums here: https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/492

Lots of helpful people.
