### ISSUE TITLE
ImportError with home-assistant v. >= 0.88.0

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/custom_components#76]
```python
Error loading custom_components.media_player.alexa. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/media_player/alexa.py", line 16, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'MEDIA_TYPE_MUSIC' from 'homeassistant.components.media_player' (/usr/local/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py)
```
[Report](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/1871)

Caused by [change in package bundling](https://rc--home-assistant-docs.netlify.com/blog/2019/02/13/release-88/):
```
Note for custom component developers: We are moving to a new file structure. Platforms now live embedded in components. Custom platforms will have to be updated to follow this pattern. This is a breaking change in case your custom platform overrides a built-in platform. Rename your custom platform from, ie light/hue.py to hue/light.py.
```

**Comment by alandtse** [comment]
This was also addressed by #75, but I didn't realize it was submitted and will use #77 to close since it has the version increment. Thanks to @akinomeroglu for his effort.

**Comment by Obicom** [comment]
Is there a outlook when a fixed version for 0.88.0 will be available? Release date for HA 0.88.0 is today 
https://rc--home-assistant-docs.netlify.com/

**Comment by alandtse** [comment]
@Obicom When it's actually live.

**Comment by Obicom** [comment]
Ok, that sound good ... I understand you are prepared ... (y)

**Comment by Obicom** [comment]
Is there anything to do with the new alexa.py for HA 0.88.0 or only exchange the file?

**Comment by alandtse** [comment]
Just replace the file for 0.88.0.  For later version of HA, they may require you rename the file and move it from media_player/alexa.py to alexa/media_player.py.  This is not a long term solution though as a later version of HA will break. The problem is HA plans to prevent partial modifications of existing components and would require a complete override.  When that happens, 1.x.y should be the main code.

**Comment by Obicom** [comment]
Thank you for explanation ...

**Comment by chali272** [comment]
> 
> 
> Just replace the file for 0.88.0. For later versions of HA, they may require you rename the file and move it from media_player/alexa.py to alexa/media_player.py. This is not a long term solution though as a later version of HA will break. The problem is HA plans to prevent partial modifications of existing components and would require a complete override. When that happens, 1.x.y should be the main code.

hi, can i alreddy change the folder to "alexa/media_player.py" or will that not work now?
//Regards

**Comment by alandtse** [comment]
@chali272 It will work for now, but will break in some point in the future.

**Comment by chali272** [comment]
> @chali272 It will work for now, but will break in some point in the future.

ok thank you. Does this support multiple account yet?  (like to ad my kids accounts)  //Regards
