### ISSUE TITLE
last_called is too slow?

### ISSUE THREAD

**Issue by matbrewer396** [keatontaylor/custom_components#83]
Hi 

I'm trying to make of the last_called attribute. Ie things like "Alexa Turn On Lights" / "Alexa Turn On TV" and then based on the echo that was used turn on the lights for that room. 

This https://github.com/keatontaylor/custom_components/pull/65 suggest that @brianhanifin got it working. But in my test there a good 10 seconds delay until the correct echo is reported back correctly. 

Is there any way to force a refresh of the last_called attribute?

Cheers

**Comment by alandtse** [comment]
Not at this time. We will be exposing a service in the future as the current polling method results in too much polling of Alexa servers.

**Comment by matbrewer396** [comment]
Yes that would be a much better option

**Comment by alandtse** [comment]
FYI, the Alexa App already allows you to do location specific control of at least lights. You'll need to use HA's emulated Hue and ensure within the AlexaApp it treats that switch as a light. I think you could also do the TV too, but I haven't tested it.

**Comment by matbrewer396** [comment]
Really, how? I've not seen this option before, do you mean via a routine? 

There only the option "Alexa will respond from" which give device specific controls

**Comment by alandtse** [comment]
https://www.amazon.com/gp/help/customer/display.html?nodeId=201749250.  Might be region specific.

**Comment by remcotim** [comment]
Alexa enabled groups. You have to  make a group in the Alexa app and add an Alexa device.
For example;
I made a group with all the lights downstairs and included the living room Echo. Same thing for all the upstairs light and the bedroom echo. 

If I ask Alexa to turn off/on the lights, when I'm downstairs, she will only switch the downstairs lights. And same for upstairs.

If you add the switch for TV as a emulated Hue, you can include that in the group.

**Comment by matbrewer396** [comment]
Nice that works thank for help

**Comment by h4nc** [comment]
@alandtse I'd like to use the last_called sensor for the following case. Unfortunately as the topic says currently it's too slow. 

I like to turn on an input boolean with a routine in alexa by my voice. This than will trigger an automation which sends a tts to the last_called alexa. This way it must be fast or it will send the tts to wrong alexa.
Will this be possible with the service you are planning to implement in future. Will the service be part of the component we already use?

**Comment by alandtse** [comment]
This [branch](https://github.com/alandtse/custom_components/tree/last_called_service) has an exposed service for the adventurous who want to test it.

`alexa_media.update_last_called` service can take no args or can specify specific accounts to find the last_called for.
```json
{
  "email" : ["email1", "email2"]
}
```
