### ISSUE TITLE
MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_type' at row 1")

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/custom_components#88]
As reported in the community [thread](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/1953):

Since we’re concatenating the email to the domain alexa_media to fire to the event_bus, we’ve hit a HA SQL table limitation during logging.

**Comment by alandtse** [comment]
Potential fix posted as #89.  Please test.

**Comment by arraylabs** [comment]
@alandtse Looks like that took care of the issue, thanks!
