### ISSUE TITLE
GPL-3.0 intake license not compatible with home-assistant Apache-2.0

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/custom_components#9]
If you're planning to upstream, you'll need to change your LICENSE to Apache-2.0 so that you can submit your addon later to the main tree.  The issue is anyone who offers you a pull request will assume you're taking their code as GPL-3.0, which cannot be converted by you to Apache-2.0 later without explicitly asking for permission to convert.  Asking to change licenses later is a pain particularly since you don't have a CLA in place.  VLC Media player went through this and you can see the pain in that experience [here](http://www.jbkempf.com/blog/post/2012/How-to-properly-relicense-a-large-open-source-project).  Based on the PR history, you seem clean of 3rd party code for now, so you may want to nip it in the bud.

Good job btw. Hope this succeeds.

**Comment by keatontaylor** [comment]
solved with #13
