### ISSUE TITLE
Error after just changing file structure name

### ISSUE THREAD

**Issue by IxsharpxI** [keatontaylor/custom_components#99]
So i was just trying to change my file naming to match the github. from alexa/media_player.py to the newer..
alexa_media/ and then the 3 files.  When i check using IDE i get this error and cant restart,"

Error: INFO:homeassistant.util.package:Attempting install of colorlog==4.0.2
Testing configuration at /config
Failed config
  General Errors: 
    - Platform not found: media_player.alexa

Successful config (partial)

**Comment by alandtse** [comment]
Please follow the [instructions](https://github.com/keatontaylor/custom_components/wiki/Configuration#installation-and-configuration) precisely. You didn't change your config.

**Comment by IxsharpxI** [comment]
i did.. i ve changed everything. to no avail..now it just says:

Component not found: alexa_media
